CREATE TABLE Rols(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	JobTitle NVARCHAR(20) NOT NULL
);

CREATE TABLE USERS(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	UsLogin VARCHAR(30) NOT NULL UNIQUE,
	UsPassword VARCHAR(40) NOT NULL,
	FIO NVARCHAR(40) NOT NULL,
	RolId INT NOT NULL DEFAULT 2,
	FOREIGN KEY (RolId) REFERENCES Rols (ID)
);

CREATE TABLE Orders(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	DateOrder DATE NOT NULL,
	NumberBox INT NOT NULL,
	StatusOrder BIT NOT NULL DEFAULT 1,
	IDWorker INT NOT NULL,
	FOREIGN KEY (IDWorker) REFERENCES Users(ID) 
);

CREATE TABLE Services(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Discriptions NVARCHAR(50) NOT NULL,

);

CREATE TABLE OrderServices(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	IDOrder INT NOT NULL,
	IDSevices INT NOT NULL,
	FOREIGN KEY (IDOrder) REFERENCES Orders(ID),
	FOREIGN KEY (IDSevices) REFERENCES Services(ID)
);